var gamedatas = gamedatas || {
	items : {
		222222 : { type : 4, subtype : 7, param1 : 7200, param2 : 1000, param3 : "", langs : {  cn : "25%出征上限提升", de : "Max. ausgezogene Soldaten um 25% erhöhen", en : "Raise troops limit by 25%", ja : "25％出陣上限プラス", ko : "부대 제한 25% 증가", ru : "Повышение максимума похода на 25%", th : "เพิ่มขีดจำกัดการบุก25%", tw : "25%出征上限提升", vi : "Tăng 25% giới hạn quân số"} },
		444444 : { type : 11, subtype : 1, param1 : 7200, param2 : 0, param3 : "", langs : {  cn : "高级召回", de : "Hochwertiger Rückruf", en : "Advanced recall", ja : "高級帰還", ko : "고급 취소", ru : "Отличный призыв", th : "เรียกกลับขั้นสูง", tw : "高級召回", vi : "Thu hổi cao cấp"} },
		666666 : { type : 4, subtype : 1, param1 : 28800, param2 : 0, param3 : "", langs : {  cn : "战争守护8小时", de : "Kriegsschutz (8 Stunden)", en : "Protective shield for 8 hrs", ja : "戦争守護8時間", ko : "8시간 보호막", ru : "Мир  на 8 ч.", th : "ป้องกันสงคราม8ชั่วโมง", tw : "戰爭守護8小時", vi : "Tấm chắn bảo vệ trong 8h"} },
		100501 : { type : 6, subtype : 6, param1 : 1, param2 : 0, param3 : "", langs : {  cn : "镇定剂", de : "Beruhigungsmittel", en : "tranquillizer", ja : "鎮静剤", ko : "진정제", ru : "Транквилизатор", th : "ยากล่อมประสาท", tw : "鎮定劑", vi : "thuốc an thần"} },
		100502 : { type : 6, subtype : 7, param1 : 50, param2 : 0, param3 : "", langs : {  cn : "狂热药剂", de : "Raserei-Trank", en : "Frenzy Potion", ja : "狂熱薬剤", ko : "용맹 약제", ru : "Зелье азарта", th : "ค่าคลั่ง ร้านขายยา", tw : "狂熱藥劑", vi : "giá trị cuồng tín tiệm thuốc tây"} },
		120001 : { type : 8, subtype : 2, param1 : 150009, param2 : 0, param3 : "", langs : {  cn : "超值月卡", de : "Wert Monatsgeschenk", en : "Vaule Monthly gift", ja : "お得なマンスリー・カード", ko : "호화로운 월간 패키지", ru : "Супер месяч. карта", th : "ของขวัญประจำเดือน", tw : "超值月卡", vi : "Quà giá trị hàng tháng"} },
		120003 : { type : 8, subtype : 2, param1 : 150010, param2 : 0, param3 : "", langs : {  cn : "超值加速月卡", de : "Beschleunigung Monatliche Karte", en : "Acceleration Monthly Card", ja : "加速マンスリー・カード", ko : "월간 가속 패키지", ru : "Месяч. карта суперскорости", th : "การเร่งความเร็วบัตรรายเดือน", tw : "超值加速月卡", vi : "Acceleration thẻ hàng tháng"} },
		120002 : { type : 8, subtype : 2, param1 : 150100, param2 : 0, param3 : "", langs : {  cn : "普通月卡", de : "Normales Monatsgeschenk", en : "Ordinary Monthly gift", ja : "普通マンスリー・カード", ko : "일반 월정액", ru : "Месяч. карта I", th : "ของขวัญประจำเดือนแบบธรรมดา", tw : "普通月卡", vi : "Quà thường hàng tháng"} },
		120005 : { type : 8, subtype : 2, param1 : 150011, param2 : 0, param3 : "", langs : {  cn : "作战手册月卡", de : "Kriegsbuch Monatliche Karte", en : "War book Monthly Card", ja : "作戦マニュアル月卡", ko : "월간 전쟁경보 패키지", ru : "Месяч. карта боевых справочников", th : "หนังสือสงครามบัตรรายเดือน", tw : "作戰手冊月卡", vi : "Thẻ tháng cuốn sách Chiến tranh"} },
		120004 : { type : 8, subtype : 2, param1 : 150101, param2 : 0, param3 : "", langs : {  cn : "高级月卡", de : "Hochwertiges Monatsgeschenk", en : "Advanced Monthly gift", ja : "高級マンスリー・カード", ko : "고급 월정액", ru : "Месяч. карта II", th : "ของขวัญประจำเดือนขั้นสูง", tw : "高級月卡", vi : "Quà cao cấp hàng tháng"} },
		120007 : { type : 8, subtype : 2, param1 : 150013, param2 : 0, param3 : "", langs : {  cn : "军官道具月卡", de : "Offizier Artikel Monatliche Karte", en : "Officer Item Monthly Card", ja : "士官道具マンスリー・カード", ko : "월간 장교 패키지(아이템)", ru : "Месяч. карта предметов офицера", th : "บัตรรายเดือนเจ้าหน้าที่รายการ", tw : "軍官道具月卡", vi : "Thẻ tháng Officer mục"} },
		120006 : { type : 8, subtype : 2, param1 : 150012, param2 : 0, param3 : "", langs : {  cn : "军官经验月卡", de : "Offizier Exp Monatliche Karte", en : "Officer Exp Monthly Card", ja : "士官経験マンスリー・カード", ko : "월간 장교 패키지(경험치)", ru : "Месяч. карта опыта офицера", th : "เจ้าหน้าที่บัตรรายเดือนประสบการณ์", tw : "軍官經驗月卡", vi : "Thẻ tháng Exp đốc"} },
		110001 : { type : 200, subtype : 1, param1 : 1, param2 : 3, param3 : "29;168", langs : {  cn : "2级反坦克攻击零件", de : "Lv 2 Panzerabwehrkanone-Angriffsbauteil", en : "Lv.2 Antitank ATK widget", ja : "2級突撃砲攻撃部品", ko : "레벨 2 구축전차 공격 부품", ru : "Деталь атаки антитанкового орудия II", th : "อะไหล่หน่วยต้านรถถังขั้น2", tw : "2級反坦克攻擊零件", vi : "Phụ tùng chống tăng ATK LV2"} },
		110000 : { type : 200, subtype : 1, param1 : 0, param2 : 3, param3 : "29;84", langs : {  cn : "1级反坦克攻击零件", de : "Lv 1 Panzerabwehrkanone-Angriffsbauteil", en : "Lv.1 Antitank ATK widget", ja : "1級突撃砲攻撃部品", ko : "레벨 1 구축전차 공격 부품", ru : "Деталь атаки антитанкового орудия I", th : "อะไหล่หน่วยต้านรถถังขั้น1", tw : "1級反坦克攻擊零件", vi : "Phụ tùng chống tăng ATK LV1"} },
		110003 : { type : 200, subtype : 1, param1 : 3, param2 : 3, param3 : "29;378", langs : {  cn : "4级反坦克攻击零件", de : "Lv 4 Panzerabwehrkanone-Angriffsbauteil", en : "Lv.4 Antitank ATK widget", ja : "4級突撃砲攻撃部品", ko : "레벨 4 구축전차 공격 부품", ru : "Деталь атаки антитанкового орудия IV", th : "อะไหล่หน่วยต้านรถถังขั้น4", tw : "4級反坦克攻擊零件", vi : "Phụ tùng chống tăng ATK LV4"} },
		110002 : { type : 200, subtype : 1, param1 : 2, param2 : 3, param3 : "29;252", langs : {  cn : "3级反坦克攻击零件", de : "Lv 3 Panzerabwehrkanone-Angriffsbauteil", en : "Lv.3 Antitank ATK widget", ja : "3級突撃砲攻撃部品", ko : "레벨 3 구축전차 공격 부품", ru : "Деталь атаки антитанкового орудия III", th : "อะไหล่หน่วยต้านรถถังขั้น3", tw : "3級反坦克攻擊零件", vi : "Phụ tùng chống tăng ATK LV3"} },
		110005 : { type : 200, subtype : 1, param1 : 5, param2 : 0, param3 : "29;672", langs : {  cn : "6级反坦克攻击零件", de : "Lv 6 Panzerabwehrkanone-Angriffsbauteil", en : "Lv.6 Antitank ATK widget", ja : "6級突撃砲攻撃部品", ko : "레벨 6 구축전차 공격 부품", ru : "Деталь атаки антитанкового орудия VI", th : "อะไหล่หน่วยต้านรถถังขั้น6", tw : "6級反坦克攻擊零件", vi : "Phụ tùng chống tăng ATK LV6"} },
		110004 : { type : 200, subtype : 1, param1 : 4, param2 : 3, param3 : "29;504", langs : {  cn : "5级反坦克攻击零件", de : "Lv 5 Panzerabwehrkanone-Angriffsbauteil", en : "Lv.5 Antitank ATK widget", ja : "5級突撃砲攻撃部品", ko : "레벨 5 구축전차 공격 부품", ru : "Деталь атаки антитанкового орудия V", th : "อะไหล่หน่วยต้านรถถังขั้น5", tw : "5級反坦克攻擊零件", vi : "Phụ tùng chống tăng ATK LV5"} },
		110007 : { type : 200, subtype : 2, param1 : 1, param2 : 3, param3 : "30;168", langs : {  cn : "2级坦克攻击零件", de : "Lv 2 Panzer-Angriffsbauteil", en : "Lv.2 Tank ATK widget", ja : "2級MBT攻撃部品", ko : "레벨 2 MBT 공격 부품", ru : "Деталь атаки танка II", th : "อะไหล่โจมตีรถถังขั้น2", tw : "2級坦克攻擊零件", vi : "Phụ tùng xe tăng ATK LV2"} },
		110006 : { type : 200, subtype : 2, param1 : 0, param2 : 3, param3 : "30;84", langs : {  cn : "1级坦克攻击零件", de : "Lv 1 Panzer-Angriffsbauteil", en : "Lv.1 Tank ATK widget", ja : "1級MBT攻撃部品", ko : "레벨 1 MBT 공격 부품", ru : "Деталь атаки танка I", th : "อะไหล่โจมตีรถถังขั้น1", tw : "1級坦克攻擊零件", vi : "Phụ tùng xe tăng ATK LV1"} },
		110009 : { type : 200, subtype : 2, param1 : 3, param2 : 3, param3 : "30;378", langs : {  cn : "4级坦克攻击零件", de : "Lv 4 Panzer-Angriffsbauteil", en : "Lv.4 Tank ATK widget", ja : "4級MBT攻撃部品", ko : "레벨 4 MBT 공격 부품", ru : "Деталь атаки танка IV", th : "อะไหล่โจมตีรถถังขั้น4", tw : "4級坦克攻擊零件", vi : "Phụ tùng xe tăng ATK LV4"} },
		110008 : { type : 200, subtype : 2, param1 : 2, param2 : 3, param3 : "30;252", langs : {  cn : "3级坦克攻击零件", de : "Lv 3 Panzer-Angriffsbauteil", en : "Lv.3 Tank ATK widget", ja : "3級MBT攻撃部品", ko : "레벨 3 MBT 공격 부품", ru : "Деталь атаки танка III", th : "อะไหล่โจมตีรถถังขั้น3", tw : "3級坦克攻擊零件", vi : "Phụ tùng xe tăng ATK LV3"} },
		110011 : { type : 200, subtype : 2, param1 : 5, param2 : 0, param3 : "30;672", langs : {  cn : "6级坦克攻击零件", de : "Lv 6 Panzer-Angriffsbauteil", en : "Lv.6 Tank ATK widget", ja : "6級MBT攻撃部品", ko : "레벨 6 MBT 공격 부품", ru : "Деталь атаки танка VI", th : "อะไหล่โจมตีรถถังขั้น6", tw : "6級坦克攻擊零件", vi : "Phụ tùng xe tăng ATK LV6"} },
		110010 : { type : 200, subtype : 2, param1 : 4, param2 : 3, param3 : "30;504", langs : {  cn : "5级坦克攻击零件", de : "Lv 5 Panzer-Angriffsbauteil", en : "Lv.5 Tank ATK widget", ja : "5級MBT攻撃部品", ko : "레벨 5 MBT 공격 부품", ru : "Деталь атаки танка V", th : "อะไหล่โจมตีรถถังขั้น5", tw : "5級坦克攻擊零件", vi : "Phụ tùng xe tăng ATK LV5"} },
		110013 : { type : 200, subtype : 3, param1 : 1, param2 : 3, param3 : "31;168", langs : {  cn : "2级火炮攻击零件", de : "Lv 2 Artillerie-Angriffsbauteil", en : "Lv.2 Artillery ATK widget", ja : "2級自走砲攻撃部品", ko : "레벨 2 자주포 공격 부품", ru : "Деталь атаки артилл. орудия II", th : "อะไหล่โจมตีของป้อมปืนขั้น2", tw : "2級火炮攻擊零件", vi : "Phụ tùng pháo ATK LV2"} },
		110012 : { type : 200, subtype : 3, param1 : 0, param2 : 3, param3 : "31;84", langs : {  cn : "1级火炮攻击零件", de : "Lv 1 Artillerie-Angriffsbauteil", en : "Lv.1 Artillery ATK widget", ja : "1級自走砲攻撃部品", ko : "레벨 1 자주포 공격 부품", ru : "Деталь атаки артилл. орудия I", th : "อะไหล่โจมตีของป้อมปืนขั้น1", tw : "1級火炮攻擊零件", vi : "Phụ tùng pháo ATK LV1"} },
		110015 : { type : 200, subtype : 3, param1 : 3, param2 : 3, param3 : "31;378", langs : {  cn : "4级火炮攻击零件", de : "Lv 4 Artillerie-Angriffsbauteil", en : "Lv.4 Artillery ATK widget", ja : "4級自走砲攻撃部品", ko : "레벨 4 자주포 공격 부품", ru : "Деталь атаки артилл. орудия IV", th : "อะไหล่โจมตีของป้อมปืนขั้น4", tw : "4級火炮攻擊零件", vi : "Phụ tùng pháo ATK LV4"} },
		110014 : { type : 200, subtype : 3, param1 : 2, param2 : 3, param3 : "31;252", langs : {  cn : "3级火炮攻击零件", de : "Lv 3 Artillerie-Angriffsbauteil", en : "Lv.3 Artillery ATK widget", ja : "3級自走砲攻撃部品", ko : "레벨 3 자주포 공격 부품", ru : "Деталь атаки артилл. орудия III", th : "อะไหล่โจมตีของป้อมปืนขั้น3", tw : "3級火炮攻擊零件", vi : "Phụ tùng pháo ATK LV3"} },
		110017 : { type : 200, subtype : 3, param1 : 5, param2 : 0, param3 : "31;672", langs : {  cn : "6级火炮攻击零件", de : "Lv 6 Artillerie-Angriffsbauteil", en : "Lv.6 Artillery ATK widget", ja : "6級自走砲攻撃部品", ko : "레벨 6 자주포 공격 부품", ru : "Деталь атаки артилл. орудия VI", th : "อะไหล่โจมตีของป้อมปืนขั้น6", tw : "6級火炮攻擊零件", vi : "Phụ tùng pháo ATK LV6"} },
		110016 : { type : 200, subtype : 3, param1 : 4, param2 : 3, param3 : "31;504", langs : {  cn : "5级火炮攻击零件", de : "Lv 5 Artillerie-Angriffsbauteil", en : "Lv.5 Artillery ATK widget", ja : "5級自走砲攻撃部品", ko : "레벨 5 자주포 공격 부품", ru : "Деталь атаки артилл. орудия V", th : "อะไหล่โจมตีของป้อมปืนขั้น5", tw : "5級火炮攻擊零件", vi : "Phụ tùng pháo ATK LV5"} },
		110019 : { type : 200, subtype : 4, param1 : 1, param2 : 3, param3 : "32;168", langs : {  cn : "2级特种车辆攻击零件", de : "Lv 2 Spezialfahrzeug-Angriffsbauteil", en : "Lv.2 Special vehicle ATK widget", ja : "2級特殊車両攻撃部品", ko : "레벨 2 특수차량 공격 부품", ru : "Деталь атаки спецмашины II", th : "อะไหล่โจมตีของหน่วยรถพิเศษขั้น2", tw : "2級特種車輛攻擊零件", vi : "Phụ tùng xe đặc chủng ATK LV2"} },
		110018 : { type : 200, subtype : 4, param1 : 0, param2 : 3, param3 : "32;84", langs : {  cn : "1级特种车辆攻击零件", de : "Lv 1 Spezialfahrzeug-Angriffsbauteil", en : "Lv.1 Special vehicle ATK widget", ja : "1級特殊車両攻撃部品", ko : "레벨 1 특수차량 공격 부품", ru : "Деталь атаки спецмашины I", th : "อะไหล่โจมตีของหน่วยรถพิเศษขั้น1", tw : "1級特種車輛攻擊零件", vi : "Phụ tùng xe đặc chủng ATK LV1"} },
		110021 : { type : 200, subtype : 4, param1 : 3, param2 : 3, param3 : "32;378", langs : {  cn : "4级特种车辆攻击零件", de : "Lv 4 Spezialfahrzeug-Angriffsbauteil", en : "Lv.4 Special vehicle ATK widget", ja : "4級特殊車両攻撃部品", ko : "레벨 4 특수차량 공격 부품", ru : "Деталь атаки спецмашины IV", th : "อะไหล่โจมตีของหน่วยรถพิเศษขั้น4", tw : "4級特種車輛攻擊零件", vi : "Phụ tùng xe đặc chủng ATK LV4"} },
		110020 : { type : 200, subtype : 4, param1 : 2, param2 : 3, param3 : "32;252", langs : {  cn : "3级特种车辆攻击零件", de : "Lv 3 Spezialfahrzeug-Angriffsbauteil", en : "Lv.3 Special vehicle ATK widget", ja : "3級特殊車両攻撃部品", ko : "레벨 3 특수차량 공격 부품", ru : "Деталь атаки спецмашины III", th : "อะไหล่โจมตีของหน่วยรถพิเศษขั้น3", tw : "3級特種車輛攻擊零件", vi : "Phụ tùng xe đặc chủng ATK LV3"} },
		110023 : { type : 200, subtype : 4, param1 : 5, param2 : 0, param3 : "32;672", langs : {  cn : "6级特种车辆攻击零件", de : "Lv 6 Spezialfahrzeug-Angriffsbauteil", en : "Lv.6 Special vehicle ATK widget", ja : "6級特殊車両攻撃部品", ko : "레벨 6 특수차량 공격 부품", ru : "Деталь атаки спецмашины VI", th : "อะไหล่โจมตีของหน่วยรถพิเศษขั้น6", tw : "6級特種車輛攻擊零件", vi : "Phụ tùng xe đặc chủng ATK LV6"} },
		110022 : { type : 200, subtype : 4, param1 : 4, param2 : 3, param3 : "32;504", langs : {  cn : "5级特种车辆攻击零件", de : "Lv 5 Spezialfahrzeug-Angriffsbauteil", en : "Lv.5 Special vehicle ATK widget", ja : "5級特殊車両攻撃部品", ko : "레벨 5 특수차량 공격 부품", ru : "Деталь атаки спецмашины V", th : "อะไหล่โจมตีของหน่วยรถพิเศษขั้น5", tw : "5級特種車輛攻擊零件", vi : "Phụ tùng xe đặc chủng ATK LV5"} },
		110025 : { type : 200, subtype : 5, param1 : 1, param2 : 3, param3 : "34;50", langs : {  cn : "2级反坦克防御零件", de : "Lv 2 Panzerabwehrkanone-Verteidigungsbauteil", en : "Lv.2 Antitank DEF widget", ja : "2級突撃砲防御部品", ko : "레벨 2 구축전차 방어 부품", ru : "Деталь защиты антитанкового орудия II", th : "อะไหล่ป้องกันของหน่วยต้านรถถังขั้น2", tw : "2級反坦克防禦零件", vi : "Phụ tùng chống tăng DEF LV2"} },
		110024 : { type : 200, subtype : 5, param1 : 0, param2 : 3, param3 : "34;24", langs : {  cn : "1级反坦克防御零件", de : "Lv 1 Panzerabwehrkanone-Verteidigungsbauteil", en : "Lv.1 Antitank DEF widget", ja : "1級突撃砲防御部品", ko : "레벨 1 구축전차 방어 부품", ru : "Деталь защиты антитанкового орудия I", th : "อะไหล่ป้องกันของหน่วยต้านรถถังขั้น1", tw : "1級反坦克防禦零件", vi : "Phụ tùng chống tăng DEF LV1"} },
	},
	lang: {
		cn:{info:'中文简体' , value:'cn'},
	    tw:{info:'中文繁体' , value:'tw'},
	    en:{info:'英文' , value:'en'},
	    ko:{info:'韩文' , value:'ko'},
	    de:{info:'德文' , value:'de'},
	    rn:{info:'俄文' , value:'rn'}
	},
	sciencemaster : {
		900013 : { level : "36", name : {  ar : "درع تفاعلي - معلّم ", cn : "反应装甲大师", de : "Reaktionspanzer Meister", en : "Reaction Armor Master", ja : "反応機甲部隊のマスター", ko : "반응 장갑 마스터", ru : "Мастер боевой брони", th : "โทเกราะป้องกันปฏิกิริยา", tw : "反應裝甲大師", vi : "Phản ứng Armor Master"} },
		900012 : { level : "35", name : {  ar : "درع - معلّم ", cn : "裙甲大师", de : "Rüstungsmeister", en : "Armor Master", ja : "鎧の達人", ko : "스커트 장갑 마스터", ru : "Мастер брони", th : "เกราะเจ้านาย", tw : "裙甲大師", vi : "Armor Master"} },
		900015 : { level : "38", name : {  ar : "درع متباعد الصفائح - معلّم ", cn : "间隙装甲大师", de : "Gap Rüstungsmeister", en : "Gap Armor Master", ja : "ギャップの鎧の達人", ko : "공간 장갑 마스터", ru : "Gap Доспех Master", th : "นายเกราะเกราะ", tw : "間隙裝甲大師", vi : "Gap Armor Master"} },
		900014 : { level : "37", name : {  ar : "درع السبائك - معلّم ", cn : "合金装甲大师", de : "Legierungsrüstungsmeister", en : "Alloy Armor Master", ja : "合金アーマーマスター", ko : "합금 장갑 마스터", ru : "Мастер сплавов", th : "ปริญญาโทเกราะโลหะผสม", tw : "合金裝甲大師", vi : "Armor Armor Master"} },
		900009 : { level : "35", name : {  ar : "الأشاوس ", cn : "无畏者", de : "Die Furchtlosen", en : "The Fearless", ja : "不敵者", ko : "용감무쌍", ru : "Бесстрашный", th : "คนที่กล้าหาญ", tw : "無畏者", vi : "Các Fearless"} },
		900008 : { level : "31", name : {  ar : "دعم الهجوم - نخبة ", cn : "攻击精英", de : "Sturm Elite", en : "Assault Elite", ja : "エリートを攻撃する", ko : "공격 엘리트", ru : "Assault Elite", th : "Assault Elite", tw : "攻擊精英", vi : "Assault Elite"} },
		900011 : { level : "30", name : {  ar : "دعم معنوي - معلّم  ", cn : "鼓舞大师", de : "Inspiration Master", en : "Inspiration Master", ja : "マスターを鼓舞する", ko : "사기 충전 마스터", ru : "Мастер вдохновения", th : "ต้นแบบแรงบันดาลใจ", tw : "鼓舞大師", vi : "Inspiration Master"} },
		900010 : { level : "30", name : {  ar : "دعم معنوي - نخبة ", cn : "鼓舞精英", de : "Inspiration Elite", en : "Inspiration Elite", ja : "エリートを鼓舞する", ko : "사기 충전 엘리트", ru : "Вдохновение Elite", th : "แรงบันดาลใจ Elite", tw : "鼓舞精英", vi : "Inspiration Elite"} },
		900005 : { level : "30", name : {  ar : "دعم باليستي - معلّم  ", cn : "弹道学大师", de : "Ballistik Master", en : "Ballistics Master", ja : "弾道学のマスター", ko : "탄도학 마스터", ru : "Мастер баллистики", th : "ปริญญาโทศึก", tw : "彈道學大師", vi : "Ballistics Master"} },
		900004 : { level : "30", name : {  ar : "دعم باليستي - نخبة ", cn : "弹道学精英", de : "Ballistik Elite", en : "Ballistics Elite", ja : "弾道学のエリート", ko : "탄도학 엘리트", ru : "Баллистика Элита", th : "Ballistics Elite", tw : "彈道學精英", vi : "Ballistic Elite"} },
		900007 : { level : "30", name : {  ar : "دعم الوقود - معلّم  ", cn : "固定燃料大师", de : "Festbrennstoff-Master", en : "Solid Fuel Master", ja : "固定燃料マスター", ko : "고체 연료 마스터", ru : "Мастер твердого топлива", th : "นายเชื้อเพลิงแข็ง", tw : "固定燃料大師", vi : "Rắn nhiên liệu Master"} },
		900006 : { level : "30", name : {  ar : "دعم الوقود - نخبة ", cn : "固体燃料精英", de : "Solid Fuel Elite", en : "Solid Fuel Elite", ja : "固体燃料精華", ko : "고체 연료 엘리트", ru : "Твердая топливная элита", th : "Solid Elite เชื้อเพลิง", tw : "固體燃料精英", vi : "Solid Elite Nhiên liệu"} },
		900001 : { level : "30", name : {  ar : "دعم الذخيرة - معلّم  ", cn : "膛线大师", de : "Rifling Master", en : "Rifling Master", ja : "腔線マスター", ko : "강선 마스터", ru : "Мастер стрельбы", th : "Rifling Master", tw : "膛線大師", vi : "Rifling Master"} },
		900000 : { level : "30", name : {  ar : "دعم الذخيرة - نخبة ", cn : "膛线精英", de : "Rifling Elite", en : "Rifling Elite", ja : "腔線エリート", ko : "강선 엘리트", ru : "Рифлинг-Элит", th : "Rifling Elite", tw : "膛線精英", vi : "Rifling Elite"} },
		900003 : { level : "30", name : {  ar : "دعم الإتزان - معلّم  ", cn : "稳定器大师", de : "Stabilisator Master", en : "Stabilizer Master", ja : "スタビライザーマスター", ko : "안정 장치 마스터", ru : "Стабилизатор", th : "Stabilizer Master", tw : "穩定器大師", vi : "Stabilizer Master"} },
		900002 : { level : "30", name : {  ar : "دعم الإتزان - نخبة ", cn : "稳定器精英", de : "Stabilisator Elite", en : "Stabilizer Elite", ja : "スタビライザーエリート", ko : "안정 장치 엘리트", ru : "Элитный стабилизатор", th : "Stabilizer Elite", tw : "穩定器精英", vi : "Ổn định Elite"} },
		900024 : { level : "40", name : {  ar : "الصقر الناري ", cn : "不死鸟", de : "Phönix", en : "Phoenix", ja : "フェニックス", ko : "피닉스", ru : "Феникс", th : "ต้นอินทผลัม", tw : "不死鳥", vi : "Phượng Hoàng"} },
		900021 : { level : "38", name : {  ar : "الباسل ", cn : "尖兵", de : "Vorhut", en : "Vanguard", ja : "バンガード", ko : "첨병", ru : "авангардный", th : "แนวหน้า", tw : "尖兵", vi : "Vanguard"} },
		900020 : { level : "30", name : {  ar : "رامبو ", cn : "速射手", de : "Schnellfeuer", en : "Rapid Firer", ja : "高速点火装置", ko : "속사수", ru : "Быстрое пожаротушение", th : "นักกีฬาความเร็ว", tw : "速射手", vi : "Tốc độ bắn súng"} },
		900023 : { level : "39", name : {  ar : "الرجل الفولاذي ", cn : "钢铁勇士", de : "Stahlkrieger", en : "Steel Warrior", ja : "鋼の戦士", ko : "강철 전사", ru : "Стальной воин", th : "นักรบเหล็ก", tw : "鋼鐵勇士", vi : "Chiến binh thép"} },
		900022 : { level : "36", name : {  ar : "البرق ", cn : "闪电侠", de : "Blinken", en : "Flash", ja : "フラッシュ", ko : "플래시", ru : "вспышка", th : "แฟลช", tw : "閃電俠", vi : "Đèn flash"} },
		900017 : { level : "37", name : {  ar : "برج المدفع - معلّم ", cn : "焊接炮塔大师", de : "Schweißturmmeister", en : "Welding Turret Master", ja : "溶接砲塔のマスター", ko : "용접 포탑 마스터", ru : "Мастер сварочной башенки", th : "เครื่องเชื่อมโทราเทียร์", tw : "焊接炮塔大師", vi : "Tháp hàn tháp"} },
		900016 : { level : "36", name : {  ar : "درع منحدر - معلّم ", cn : "无缝装甲大师", de : "Nahtloser Rüstungsmeister", en : "Seamless Armor Master", ja : "シームレスな鎧の達人", ko : "매끄러운 장갑 마스터", ru : "Мастер бесшовных доспехов", th : "นายเกราะไม่มีรอยต่อ", tw : "無縫裝甲大師", vi : "Sư tỷ giá"} },
		900019 : { level : "39", name : {  ar : "درع الطاقة - معلّم ", cn : "溃能装甲大师", de : "Energierüstungsmeister", en : "Energy Armor Master", ja : "エネルギーの鎧の達人", ko : "접이식 장갑 마스터", ru : "Мастер энергетической брони", th : "ปริญญาโทเกราะพลังงาน", tw : "潰能裝甲大師", vi : "Năng lượng Armor Master"} },
		900018 : { level : "38", name : {  ar : "هيكل صلب خاص - معلّم ", cn : "防崩落结构大师", de : "Anti-Kollaps-Struktur-Master", en : "Anti-collapse Structure Master", ja : "反崩壊構造マスター", ko : "안티 동굴 구조 마스터", ru : "Мастер по борьбе с коллапсом", th : "โครงสร้างโครงสร้างป้องกันการยุบ", tw : "防崩落結構大師", vi : "Chống sụp đổ cơ cấu Thạc sĩ"} },
   },
	tempactivation : [
			{ dialog : "0",dataid : "1418",name : "建筑10级活动",type : "建筑等级", },
			{ dialog : "0",dataid : "1419",name : "建筑13级活动",type : "建筑等级", },
			{ dialog : "0",dataid : "1420",name : "建筑16级活动",type : "建筑等级", },
			{ dialog : "0",dataid : "1421",name : "建筑19级活动",type : "建筑等级", },
			{ dialog : "0",dataid : "1422",name : "建筑22级活动",type : "建筑等级", },
			{ dialog : "0",dataid : "1373",mail : "",name : "提升战斗力220W",type : "提升战力",value : "2200000", },
			{ dialog : "0",dataid : "1374",mail : "",name : "提升战斗力180W",type : "提升战力",value : "1800000", },
			{ dialog : "0",dataid : "1375",mail : "",name : "提升战斗力30W",type : "提升战力",value : "300000", },
			{ dialog : "0",dataid : "1605",mail : "",name : "全部军官战力到达240万",type : "提升军官战力",value : "2400000", },
			{ dialog : "0",dataid : "1606",mail : "",name : "全部军官战力到达180万",type : "提升军官战力",value : "1800000", },
			{ dialog : "0",dataid : "1607",mail : "",name : "全部军官战力到达100万",type : "提升军官战力",value : "1000000", },
			{ dialog : "0",dataid : "1608",mail : "",name : "全部军官战力到达30万",type : "提升军官战力",value : "300000", },
			{ dialog : "0",dataid : "1610",mail : "",name : "至少1名军官等级到达40级",type : "军官等级",value : "40", },
			{ dialog : "0",dataid : "1611",mail : "",name : "至少1名军官等级到达25级",type : "军官等级",value : "25", },
			{ dialog : "0",dataid : "1612",mail : "",name : "至少1名军官等级到达10级",type : "军官等级",value : "10", },
			{ dialog : "0",dataid : "1632",mail : "",name : "至少1名军官等级到达50级",type : "军官等级",value : "50", },
			{ dialog : "0",dataid : "1614",mail : "",name : "至少1名军官勋章等级到达10级",type : "军官勋章等级",value : "10", },
			{ dialog : "0",dataid : "1615",mail : "",name : "至少1名军官勋章等级到达9级",type : "军官勋章等级",value : "9", },
			{ dialog : "0",dataid : "1616",mail : "",name : "至少1名军官勋章等级到达8级",type : "军官勋章等级",value : "8", },
			{ dialog : "0",dataid : "1617",mail : "",name : "至少1名军官勋章等级到达7级",type : "军官勋章等级",value : "7", },
			{ dialog : "0",dataid : "1618",mail : "",name : "至少1名军官勋章等级到达6级",type : "军官勋章等级",value : "6", },
			{ dialog : "0",dataid : "1619",mail : "",name : "至少1名军官勋章等级到达5级",type : "军官勋章等级",value : "5", },
			{ dialog : "0",dataid : "1620",mail : "",name : "至少1名军官勋章等级到达4级",type : "军官勋章等级",value : "4", },
			{ dialog : "0",dataid : "1621",mail : "",name : "至少1名军官勋章等级到达3级",type : "军官勋章等级",value : "3", },
			{ dialog : "0",dataid : "1622",mail : "",name : "至少1名军官勋章等级到达2级",type : "军官勋章等级",value : "2", },
			{ dialog : "0",dataid : "1624",mail : "",name : "至少1名军官4条被动技能属性全红色以上",type : "军官被动技能",value : "5", },
			{ dialog : "0",dataid : "1625",mail : "",name : "至少1名军官4条被动技能属性全橙色以上",type : "军官被动技能",value : "4", },
			{ dialog : "0",dataid : "1626",mail : "",name : "至少1名军官4条被动技能属性全紫色以上",type : "军官被动技能",value : "3", },
			{ dialog : "0",dataid : "1627",mail : "",name : "至少1名军官4条被动技能属性全蓝色以上",type : "军官被动技能",value : "2", },
			{ dialog : "0",dataid : "1628",mail : "",name : "至少1名军官4条被动技能属性全绿色以上",type : "军官被动技能",value : "1", },
			{ dialog : "0",dataid : "1601",name : "军官战力排行榜",type : "军官排行榜", },
			{ dataid : "1736",name : "热销商店",type : "2017新运营活动", },
			{ dataid : "1737",name : "消耗金币",type : "2017新运营活动", },
			{ dataid : "1738",name : "战争之王",type : "2017新运营活动", },
			{ dataid : "1739",name : "抽奖返利",type : "2017新运营活动", },
			{ dataid : "1740",name : "加速成长",type : "2017新运营活动", },
			{ dataid : "1741",name : "造兵回馈",type : "2017新运营活动", },
			{ dataid : "1745",name : "科技爆发",type : "2017新运营活动", },
			{ dataid : "1747",name : "充值送大礼活动",type : "2017新运营活动", },
			{ dataid : "1752",name : "超级联盟",type : "2017新运营活动", },
			{ dataid : "1753",name : "超值返还",type : "2017新运营活动", },
			{ dataid : "1754",name : "买一送一",type : "2017新运营活动", },
			]
};

export default gamedatas;